@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Agency{
    location
    emailAddres;
    phoneNumber
}
class Agent {
id/email
password
}

class Location{
street
city
state
zip code
}

class Owner {
id/email
password
emailAddres
}

class Property {
   type
   area
   location
    distance_from_the_city_center
}

class Announcement {
announcementId
     property
  }
 class Commision {
     type_of_comission
     comissionValue
     }

Owner "1" -- "1..*" Agent : selects an >
Owner "1" -- "1..*" Property : owns a >
Agent "1" -- "1..*" Announcement : publishes an >
Agent "1..*" -- "1" Agency : works for >
Property "1"-- "1..*"Announcement: is needed for  >
Location "1"--"1" Property : is needed for >
Location "1"--"1" Agency : is needed for >
Commision "1"--"1" Announcement : is needed for >

@enduml