@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model


class Employee{
name
citizen_card_number
tax_number
address
email_address
contact
employeeRole
assignedAgency
}
class Agent{
name
citizen_card_number
tax_number
address
email_address
}

class SystemAdministrator{
id/email
password
}

class Land{
property
}


class Agency{
id
designation
location
phone_number
email_address
}

class UnregisteredUser{
id/email
password
}


class Property {
    type
    area
    location
    distance_from_the_city_centre
    requested_price
    photos
    propertyType
    }

class Announcement {
       AnnouncementId;
           request;
          commission;
        date;
          announcementOrdersAvailable
         announcementOrdersAccepted


      }

class Apartment{
    number_of_bedrooms
    number_of_bathrooms
    number_of_parking_spaces
    existence_of_central_heating
    existence_of_air_conditioning
}

class House{
    number_of_bedrooms
    number_of_bathrooms
    number_of_parking spaces
    existence_of_central heating
    existence_of_air_conditioning
    existence_of_a_basement
    existence_of_an_inhabitable_loft
    existence_of_sun_exposure
}


class Request{
RequestId;
 property;
 typeBusiness;
 price;
owner;
requestDate
contractDuration

date
}




class Owner{
   name;
     ccNumber;
   taxNumber;
     emailAddress;
 phoneNumber;
}





class Order{
OrderId;
 orderValue;
 orderDate;
}
class Client{
clientId;
 clientName;
 phoneNumber;
 clientEmail;
}





Agent "1..*" -- "1..*" Request : receives a  >
Agent "1..*" -- "1" Request: selects a request from >
Property "1"-- "1..*"Announcement: is needed for  >
Property "1"-- "1"Request: is needed for  >
Request "1..*"-- "1..*"Announcement: can be converted  to  >
Agent "1" -- "1..*" Announcement : publishes an >

Agent "1..*" -- "1..*" Agency : works for >
SystemAdministrator "1" -- "*" Employee : registers an >
SystemAdministrator "1" -- "*" Employee : defines the role for >
Owner "1" -- "1..*" Property : owns a >
Property "1" -- "1" House :  can be a >
Property "1" -- "1" Apartment :  can be a >
Property "1" -- "1" Land :  can be a >
UnregisteredUser "1..*" -- "1..*" Agent :  can be an >
UnregisteredUser "1..*" -- "1::*" Owner :  can be an >
UnregisteredUser "1..*" -- "1..*" Employee :  can be an >
UnregisteredUser "1..*" -- "1..*" SystemAdministrator :  can be a >

Owner "1" -- "1..*" Agent : selects an  >


Employee "1" -- "1" Agent : can be >

Agency "1" -- "1..*" Property : lists >

Agent "1" -- "1" Owner :  answer the visit request >
Agent "1" -- "1" Owner :  sends a message to  >
Agent "1" -- "1" Property : reservs a >

Request "1" --> "1" Property: is needed for  <
Request"1" --> "1" Announcement: is needed for  >
Client "1" -- "1..*" Order : places a >
Agent "1" -- "1..*" Order : lists >
Agent "1" -- "1*" Order : accepts or declines >


@enduml