@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":PublishAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "propertyRepository:\nPropertyRepository" as PropertyRepository

autonumber 14
-> CTRL : getPropertyByLocation(propertyLocation)

autonumber 14.1

activate CTRL
    group Get Property
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getPropertyRepository()
        activate PLAT

            PLAT -> CTRL : propertyRepository
        deactivate PLAT

        CTRL -> PropertyRepository : getLocationByLocation(propertyLocation)
        activate PropertyRepository

            PropertyRepository --> CTRL : propertyList
        deactivate PropertyRepository

    end group

    autonumber 15
    <-- CTRL : propertyList

deactivate CTRL


@enduml