@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Owner" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new request
    activate System

        System --> Employee : shows type of request list
    deactivate System

    Employee -> System : selects type of request
    activate System

        System --> Employee : shows type of property list

    deactivate System

    Employee -> System : selects type of property
    activate System

        System --> Employee : request data
    deactivate System

    Employee -> System : types requested data(property area, location, distance from city centre, price)

     activate System

        System --> Employee : request data
    deactivate System


@enduml