  @startuml
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Agent {
id/email
password
}

class  RequestList{
date
property
}


class Owner {
}
class Location{
street
city
state
zip code
}

class Property {
   area
   location
    distance_from_the_city_center
}

class Announcement {
  property
    description
    comission
  }

Agent "1..*" -- "1" Agency : works for  >
Owner "1" -- "1" RequestList: request a property announcment to >
Agent "1" -- "1" RequestList: selects a request from >
Property "1"-- "1"Announcement: is needed for  >
Property "1"-- "1"RequestList: is needed for  >
Owner "1" -- "1..*" Property : owns a >
Location "1"--"1" Property : is needed for>

Agent "1" -- "1..*" Announcement : publishes an >


@enduml