@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "System Administrator" as Administrator
participant "System" as System
participant "Store" as Store

activate Administrator

    Administrator -> Store : asks to obtain information about the designation, location and local manager
    activate Store

        Store --> Administrator : send information
    deactivate Store

    Administrator -> System : insert information
    activate System

    System -> System : sort information

        Store --> Administrator : send information
    deactivate Store

    Administrator -> Store : submits data
    activate Store

        Store --> Administrator : displays operation success
    deactivate Store

@enduml