@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title User Story 002 - System Sequence Diagram (SSD)


autonumber



actor "Real Estate Agent" as Agent
participant "System" as System


activate System
activate Agent


    System -> Agent: asks for property data
    deactivate System


    Agent -> System :registers  all necessary data of the property

    activate System

    System-> Agent:asks for a  comission
     deactivate System
   Agent-> System:sends comission

   activate System
System -> Agent : informs the agent that the announcment has been published
deactivate System










@enduml