@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class Property{
    type_of_property
    area
    location
    distance_from_the_city_centre
    requested_price
}


class Request {
       type_of_request
       owner
}
class Land{

}

class Agent{
    userName
    phoneNumber
    é mais fofo que a jeanette
}

class Request_Repository{
}

class Apartment{
    number_of_bedrooms
    number_of_bathrooms
    number_of_parking_spaces
    existence_of_central_heating
    existence_of_air_conditioning
}

class House{
    number_of_bedrooms
    number_of_bathrooms
    number_of_parking spaces
    existence_of_central heating
    existence_of_air_conditioning
    existence_of_a_basement
    existence_of_an_inhabitable_loft
    existence_of_sun_exposure
}

Property -u-> Land: can be a
Property -l-> Apartment : can be an
Property -r-> House : can be an
Request-u->Property : of
Request_Repository->Request
Agent -l-> Request : list

@enduml