@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)
autonumber

actor "Organization Employee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : request a list of booking requests for properties managed by him
    activate System

        System --> Employee : request the begin date of the requests
    deactivate System

    Employee -> System : submit the begin date of the requests
    activate System

        System --> Employee : request the end date of the requests
    deactivate System

    Employee -> System : submit the end date of the requests
    activate System

        System --> Employee : shows the list sorted by date(ascending)
    deactivate System



@enduml