@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)
autonumber

actor "Organization Employee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Request a list of booking requests for properties managed by him
    activate System

        System --> Employee : Request the begin date of the requests
    deactivate System

    Employee -> System : Submit the begin date of the requests
    activate System

        System --> Employee : Request the end date of the requests
    deactivate System

    Employee -> System : Submit the end date of the requests
    activate System

    System --> Employee : Shows details and asks confirmation
    deactivate System

    Employee --> System : Confirms all data
    activate System

    System --> Employee : Shows the sorted list of all booking requests
    deactivate System



@enduml