@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model


class Agent{
    userName
    phoneNumber
}

class Property{
       type of property
       area
       distance from center
       price
       state
       zipCode
}


class VisitRequest{
    client
    phoneNumber
    timeSlot
    date
}

class Owner{
    userName
    phoneNumber
}

class Response {
    -typeEmail
    -response
    -userName
    -phoneNumber
}

class TypeEmail{
    typeEmail
}

class Response {

}

Agent -l-> VisitRequest :  view
Agent -> Response : write
Response -> Owner : is sent
Response -u-> TypeEmail
Property -> VisitRequest : has
Owner -d-> VisitRequest : request
VisitRequest -r-> Response: has
@enduml