@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Real Estate Agent" as Agent
participant ":PublishAnnouncementUI" as UI
participant ":PublishAnnouncementController" as CTRL
participant ":Repositories" as Repositories
participant "repositories :Repositories" as RPS
participant "AuthenticationRepository" as AuthenticationRepository
participant "AnnouncementRepository" as AnnouncementRepository
activate Agent


Agent -> UI : displayAndSelectAnnouncements()
activate UI

UI --> CTRL** : new PublishAnnouncementController()
UI -> CTRL : getAnnouncement()
activate CTRL

    ref over CTRL, AnnouncementRepository : Announcements

    CTRL -> Repositories : getInstance()
    activate Repositories
    Repositories --> CTRL : repositories
    deactivate Repositories

    CTRL -> RPS : getAnnouncementRepository()
    activate RPS
    RPS --> CTRL : announcementRepository
    deactivate RPS
    CTRL -> AnnouncementRepository : getAnnouncementById();
    AnnouncementRepository -> announcementRepository : getAnnouncementById();






deactivate CTRL
deactivate UI
deactivate Agent
@enduml
