@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Real Estate Agent" as Agent
participant ":PublishAnnouncementUI" as UI
participant ":PublishAnnouncementController" as CTRL
participant ":Repositories" as Repositories
participant "repositories :Repositories" as RPS
participant "AuthenticationRepository" as AuthenticationRepository
participant "AnnouncementRepository" as AnnouncementRepository
participant "MessageController" as MessageController
participant "Owner" as Owner
participant "Message" as Message
participant "Commission" as Commission

activate Agent

Agent -> UI : displayAndSelectAnnouncements()
activate UI

UI --> CTRL** : new PublishAnnouncementController()
UI -> CTRL : getAnnouncement()
activate CTRL

CTRL -> Repositories : getInstance()
activate Repositories
Repositories --> CTRL : repositories
deactivate Repositories

CTRL -> RPS : getAnnouncementRepository()
activate RPS
RPS --> CTRL : announcementRepository
deactivate RPS
CTRL -> AnnouncementRepository : getAnnouncementById()
activate AnnouncementRepository
AnnouncementRepository --> CTRL : announcementId
deactivate AnnouncementRepository
CTRL --> UI : announcement
deactivate CTRL
UI -> UI : createAnnouncementView(announcement)
UI -> UI : displayAnnouncementView()

deactivate UI
@enduml
