@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Agent {
name
phoneNumber
role;
id/email
password
}
class Owner{
name
phoneNumber


}
class Message{
agent
owner
property

}






class Property {
   type
   area
   location
    distance_from_the_city_center
    propertyId

}

class Announcement {
announcementId
commision
property
  }
 class Commision {
     type_of_comission
     comissionValue
     }

Owner "1" -- "1..*" Property : owns a >
Agent "1" -- "1..*" Announcement : publishes an >
Announcement "1"-- "1..*" Property: contains >
Announcement"1"--"1" Commision : needs >
Owner "1"--"1" Message : receives a >
Agent "1"--"1" Message : sends a
Message "1"--"1" Property : has information of >
@enduml