@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Organization Employee" as Employee
participant ":System" as System

activate Employee


    Employee -> System : request a list of available properties
    activate System

        System --> Employee : shows the list of available properties
    deactivate System

    Employee -> System : asks to sort from the most recent entries to the oldest
    activate System

        System --> Employee : shows sorted list
    deactivate System


    Employee -> System : made a request for visit a property \n(selects an available property, client's name,\n phone number, preferred date and time slot)
    activate System

        System --> Employee : shows data
    deactivate System

opt the  request is valid and registered

     Employee -> System : submit data
        activate System

        System --> Employee : shows a success message
    deactivate System
end

opt if the requests don't overlap each other
loop  if the requests don't overlap each other
    Employee -> System : made a request for visit a property \n(selects an available property, client's name,\n phone number, preferred date and time slot)
        activate System


            System --> Employee : shows data
        deactivate System

opt  the request is valid and registered

     Employee -> System : submit data
        activate System

        System --> Employee : shows a success message
    deactivate System

end
end
end

Employee -> System : confirm data

     activate System

            System --> Employee : display operation sucess
     deactivate System



@enduml