@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


'title Domain Model

'class Platform {
'  -description
'}
class Property  {
    type of property
    area in m2
    location
    distance from the city centre
    requested price
    one or more photos
}

class Owner{
    name
    citize's card number
    tax number
    adress
    email adress
    contact telephone number
    agency
}

class Apartment{
    number of bedrooms
    number ofs bathrooms
    number of parking spaces
    existence of central heating
    existence of air conditioning

}
class House{
    number of bedrooms
    number ofs bathrooms
    number of parking spaces
    existence of central heating
    existence of air conditioning
    existence of a basement
    existence of an inhabitable loft
    existence of sun exposure
}


class Agent {
    name
    citize's card number
    tax number
    adress
    email adress
    contact telephone number
    agency
}

'class User {
'    name
'    email
'    password
'}

'Platform  -- "*" Owner : has registered >
'Platform -- "*" Category : defines >
Property "1"-D-> "1..*" House :  can be a
Property "1    "-U-> "1..* " Apartment :  can be an
Property "1"->"0" Owner : has an
Owner "1"-> "0" Agent : contracts an



@enduml