@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title User Story 002 - System Sequence Diagram (SSD)


autonumber



actor "Real Estate Agent" as Agent
participant "System" as System



activate Agent

loop While login data is  not valid
activate System
System --> Agent : requests login
deactivate System
Agent -> System : inserts loign data (id/email , password )
alt login is not valid
activate System
System --> Agent : displays error message

end
end

activate System
loop while the agent declines the announcement submission


System --> Agent: displays agent menu

deactivate System
 Agent -> System : selects to publish an announcement

 activate System

 System --> Agent: asks for the type of commission (fixed value  or percentage)

   deactivate System
    Agent-> System: selects the type of commission.



      loop While commission is not valid
      activate System
      System --> Agent: Asks to insert commission.
      deactivate System

       Agent -> System:  inserts commission.

       alt commission is not valid
       activate System
       System --> Agent : displays error message
       end
       end


   System --> Agent : displays announcement  data(id,type of commisson,commisson value ,date) and asks for announcement publishment confirmation
   deactivate System

alt
  Agent -> System : declines the announcement confirmation
  activate System
  end
  end
  System --> Agent: displays success message  (informs the agent the announc,ment has been published)
   deactivate System
deactivate Agent











@enduml