@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "System Administrator" as Administrator
participant ":System" as System


activate Administrator

    Administrator -> System : asks to create a new store
    activate System
        System --> Administrator : requests data
        deactivate System

    Administrator -> System : types requested data (id, designation, \ne-mail address, \ncontact telephone number), \nport number and zip code)
    activate System
        System --> Administrator: shows state list
        deactivate System

    Administrator -> System: selects state
    activate System
        System --> Administrator: shows district list
        deactivate System

    Administrator -> System: selects district
    activate System
        System --> Administrator: shows city list
        deactivate System

    Administrator -> System: selects city
    activate System
        System --> Administrator: shows data
        deactivate System

    Administrator -> System : submits data
    activate System
        System --> Administrator : Shows operation success
        deactivate System

@enduml