@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction


class Store {
    - Integer id
    - String designation
    - Integer portNumber
    - Integer zipCode
    - String emailAddress
    - String phoneNumber

    + Store(id, designation, state, district,\ncity, emailAddress, telephoneNumber)
}

class TaskCategory {
    - String description

    + TaskCategory(description)
}

class Company {
    - addStore(store)
    - validateStore(store)
    + registerStore(id, designation, state, district,\ncity, emailAddress, telephoneNumber)

'  +saveStore(store)
}

class LocationRepository {
}

class OrganizationRepository {
    + getOrganizationByEmployeeEmail(email)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getTaskCategoryRepository()
    + getOrganizationRepository()
}

class RegisterStoreController {
    + RegisterStoreController(locationRepository)
    + getStates()
    + getDistricts(state)
    + getCities(state, district)
    + createTask(userEmail, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, categoryDescription)
    - getTaskCategoryByDescription(taskCategoryDescription)
    - getEmployeeFromSession()
}

note right of RegisterStoreController
    - userEmail is obtained
    from the user session
    - categoryDescription
    is retrieved from selected data
end note

note bottom of LocationRepository
    - used for displaying
    the category list
end note

class CreateTaskUI {
}

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

CreateTaskUI .> RegisterStoreController

RegisterStoreController .> Repositories : repositories

Repositories -> "1" LocationRepository

RegisterStoreController ..> TaskCategory
RegisterStoreController ..> OrganizationRepository : organizationRepository
RegisterStoreController ..> LocationRepository : LocationRepository

Repositories --> "1" OrganizationRepository

OrganizationRepository --> "*" Company
ApplicationSession --> "1" UserSession : userSession

RegisterStoreController ..> "1" Company : organization
RegisterStoreController ..> ApplicationSession
RegisterStoreController ..> UserSession
Store "*" --> "1" TaskCategory : taskCategory
LocationRepository "1" --> "*" TaskCategory : taskCategory
Company "1" --> "*" Store : tasks
Store --> Employee : createdBy

Company --> "*" Employee : employs

@enduml