@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "company\n:Company" as Company
participant "store\n:Store" as Store

autonumber 20
-> Company: registerStore(id, designation, state, district, city, \nportNumber, zipCode, emailAddress, telephoneNumber)

autonumber 20.1
activate Company
    group Register Store

        Company -> Store**: register(id, designation, state, district, \ncity, portNumber, zipCode, \nemailAddress, telephoneNumber)
            Company -> Company: addStore(store)
            deactivate Store
        activate Company
            Company -> Company: validateStore(store)
            activate Company
                Company --> Company
            deactivate Company

            Company --> Company
        deactivate Company
    end

    autonumber 21
    <-- Company : store
deactivate Company


@enduml