@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant ":RegisterStoreUI" as UI
participant ":RegisterStoreController" as CTRL
participant "company\n:Company" as Company

activate ADM

    ADM -> UI : asks to register a new store
    activate UI

        UI -> CTRL** : register
        UI --> ADM: requests data
        deactivate UI

    ADM -> UI : types requested data (id, designation, \nport number, zip code, e-mail address, \nand contact telephone number)
        activate UI

UI -> CTRL : getStates()
        ref over CTRL
            Get State List


          end ref


        activate CTRL

            CTRL --> UI : stateList
            deactivate CTRL
            UI --> ADM : shows state list
        deactivate UI

    ADM -> UI : selects state
    activate UI

    UI -> CTRL : getDistricts(state)
            ref over CTRL
                Get District List


              end ref


            activate CTRL

                CTRL --> UI : districtList
                deactivate CTRL
                UI --> ADM : shows district list
            deactivate UI
    ADM -> UI: selects district
    activate UI

    UI -> CTRL : getCities(state, district)
         ref over CTRL
                        Get City List


                      end ref


                    activate CTRL

                        CTRL --> UI : cityList
                        deactivate CTRL
                        UI --> ADM : shows city list
                    deactivate UI
    ADM -> UI: selects city
    activate UI

        UI --> ADM : shows data
    deactivate UI

    ADM -> UI : submits data
    activate UI

        UI -> CTRL : registerStore(id, designation, state, district, city, \nportNumber, zipCode, emailAddress, telephoneNumber)
        activate CTRL


            CTRL -> Company: registerStore(id, designation, state, district, city, \nportNumber, zipCode, emailAddress, telephoneNumber)
            activate Company

                ref over Company
                    Register Store

                end

                Company --> CTRL : store
            deactivate Company

            CTRL --> UI: store
            deactivate CTRL
            UI --> ADM: Shows operation success
    deactivate UI

deactivate ADM

@enduml