@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":RegisterStoreController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "locationRepository:\nLocationRepository" as LocationRepository

autonumber 9

 -> CTRL : getDistricts()
autonumber 9.1
activate CTRL
    group Get District List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getLocationRepository()
            activate PLAT

                PLAT --> CTRL: locationRepository
            deactivate PLAT

            CTRL -> LocationRepository : getDistricts(state)
            activate LocationRepository

                LocationRepository --> CTRL : districtList
            deactivate LocationRepository


    end
    autonumber 10
    <-- CTRL  : districtList
deactivate CTRL


@enduml