@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant ":RegisterStoreUI" as UI
participant ":RegisterStoreController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "locationRepository:\nLocationRepository" as LocationRepository
participant "company\n:Company" as Company
participant "store\n:Store" as Store

activate ADM
ADM -> UI : asks to register a new store
    activate UI

        UI -> CTRL** : register
        UI --> ADM: requests data
        deactivate UI

    ADM -> UI : types requested data (id, designation, \nport number, zip code, e-mail address, \nand contact telephone number)
        activate UI

UI -> CTRL : getStates()
    activate CTRL
CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getLocationRepository()
            activate PLAT

                PLAT --> CTRL: locationRepository
            deactivate PLAT

            CTRL -> LocationRepository : getStates()
            activate LocationRepository

                LocationRepository --> CTRL : stateList
            deactivate LocationRepository




            CTRL --> UI : stateList
            deactivate CTRL
            UI --> ADM : shows state list
        deactivate UI

    ADM -> UI : selects state
    activate UI

    UI -> CTRL : getDistricts(state)
    activate CTRL
    CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getLocationRepository()
                activate PLAT

                    PLAT --> CTRL: locationRepository
                deactivate PLAT

                CTRL -> LocationRepository : getDistricts(state)
                activate LocationRepository

                    LocationRepository --> CTRL : districtList
                deactivate LocationRepository




                CTRL --> UI : districtList
                deactivate CTRL
                UI --> ADM : shows district list
            deactivate UI
    ADM -> UI: selects district
    activate UI

    UI -> CTRL : getCities(state, district)
    activate CTRL


    CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getLocationRepository()
                activate PLAT

                    PLAT --> CTRL: locationRepository
                deactivate PLAT

                CTRL -> LocationRepository : getCities(state, district)
                activate LocationRepository

                    LocationRepository --> CTRL : cityList
                deactivate LocationRepository

                        CTRL --> UI : cityList
                        deactivate CTRL
                        UI --> ADM : shows city list
                    deactivate UI
    ADM -> UI: selects city
    activate UI

        UI --> ADM : shows data
    deactivate UI

    ADM -> UI : submits data
    activate UI

        UI -> CTRL : registerStore(id, designation, state, district, city, \nportNumber, zipCode, emailAddress, telephoneNumber)
        activate CTRL


            CTRL -> Company: registerStore(id, designation, state, district, city, \nportNumber, zipCode, emailAddress, telephoneNumber)
            activate Company
            Company -> Store**: register(id, designation, state, district, \ncity, portNumber, zipCode, \nemailAddress, telephoneNumber)
                        Company -> Company: addStore(store)
                        deactivate Store
                    activate Company
                        Company -> Company: validateStore(store)
                        activate Company
                            Company --> Company
                        deactivate Company

                        Company --> Company
                    deactivate Company


                Company --> CTRL : store
            deactivate Company

            CTRL --> UI: store
            deactivate CTRL
            UI --> ADM: Shows operation success
    deactivate UI
        
deactivate ADM

@enduml