@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":RegisterStoreController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "locationRepository:\nLocationRepository" as LocationRepository

autonumber 13

 -> CTRL : getCities()
autonumber 13.1
activate CTRL
    group Get City List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getLocationRepository()
            activate PLAT

                PLAT --> CTRL: locationRepository
            deactivate PLAT

            CTRL -> LocationRepository : getCities(state, district)
            activate LocationRepository

                LocationRepository --> CTRL : cityList
            deactivate LocationRepository


    end
    autonumber 14
    <-- CTRL  : cityList
deactivate CTRL


@enduml