@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction


class Store {
    - Integer id
    - String designation
    - Integer portNumber
    - Integer zipCode
    - String emailAddress
    - String phoneNumber

    + store(id, designation, state, district,\ncity, emailAddress, telephoneNumber)
}

class Company {
    - addStore(store)
    - validateStore(store)
    + registerStore(id, designation, state, district,city, \nportNumber, zipCode, emailAddress, telephoneNumber)

'  +saveStore(store)
}

class LocationRepository {
}


class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getLocationRepository()
}

class RegisterStoreController {
    + RegisterStoreController(locationRepository)
    + getStates()
    + getDistricts(state)
    + getCities(state, district)
    + registerStore(id, designation, \nstate, district, city, portNumber, \nzipCode, emailAddres, phoneNumber )
}


note bottom of LocationRepository
    - used for displaying
    the state, district
    and city lists
end note


Repositories -> Repositories : instance

RegisterStoreUI .> RegisterStoreController

RegisterStoreController .> Repositories : repositories

Repositories -> "1" LocationRepository

RegisterStoreController ..> LocationRepository : LocationRepository


RegisterStoreController ..> "1" Company : company
Company "1" --> "*" Store : has


@enduml