@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model


class Employee{
name
citizen_card_number
tax_number
address
email_address
contact
}

class EmployeeRole{
description
}

class Company{
description
}

class Agency{
}

class User{
name
email
password
}

class Store {
    id
    designation
    location
    email_address
    phone_number
}

class Property {
    type
    area
    location
    distance_from_the_city_centre
    requested_price
    photos
    }

class Announcement {
        description
        comission
      }

class Apartment{
    number_of_bedrooms
    number_of_bathrooms
    number_of_parking_spaces
    existence_of_central_heating
    existence_of_air_conditioning
}

class House{
    number_of_bedrooms
    number_of_bathrooms
    number_of_parking spaces
    existence_of_central heating
    existence_of_air_conditioning
    existence_of_a_basement
    existence_of_an_inhabitable_loft
    existence_of_sun_exposure
}

SystemAdministrator "1" -- "*" Employee : registers >
Employee "*" -- "1" Agency : is assigned to >
Company "1" -- "1" SystemAdministrator : has >
Employee "1" -- "1" EmployeeRole :  has >
SystemAdministrator "1" -- "*" EmployeeRole : defines >
SystemAdministrator "1" -- "1" User : is >
Employee "1" -- "1" User : is >
Company "1" -- "1..*" Agency : has >
SystemAdministrator "1" -- "*" Store : registers >
Store "1..*" -- "1" StoreManager : managed by >
StoreManager "1" -- "1" User : is >
Owner "1" -- "1" Agent : selects >
Owner "1" -- "1..*" Property : owns >
Agent "1" -- "1..*" Announcement : publishes >
Agency "1" -- "1..*" Agent : has >
Agent "1" -- "1" User : is >
Owner "1" -- "1" User : is >
Property "1" -- "*" House :  can be >
Property "1" -- "*" Apartment :  can be >

@enduml