@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant ":ImportInformationUI" as UI
participant ":ImportInformationController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant ":Repositories" as Rep
participant "repositories\n:Repositories" as PLAT
participant "propertyTypeRepository\n:PropertyTypeRepository" as ProType
participant "typeOfBusinessRepository\n:TypeOfBusinessRepository" as TypeOfBusinessRepository
participant "employeeRepository\n:EmployeeRepository" as EmployeeRepository
participant "propertyRepository\n:PropertyRepository" as PropertyRepository
participant "requestRepository\n:RequestRepository" as RequestRepository
participant "announcementRepository\n:AnnouncementRepository" as AnnouncementRepository
participant "agencyRepository\n:AgencyRepository" as AgencyRepository

activate ADM

    ADM -> UI : asks to import information from a legacy system

autonumber 1.1
    activate UI

        UI -> CTRL** : import

autonumber 2
        UI --> ADM : requests data
    deactivate UI

    ADM -> UI : types requested data (fileName)
    activate UI

        UI --> ADM : shows selected data and asks to confirm data
    deactivate UI

    ADM -> UI : confirms data
    activate UI
        autonumber 5.1
        UI -> CTRL : readFile(fileName)
        activate CTRL

            CTRL -> CTRL : getPropertyTypeByName(String propertyTypeName)
            activate CTRL

                autonumber 5.1.1
                activate CTRL
                    CTRL -> Rep : getInstance()

                    activate Rep

                    Rep --> CTRL: repositories
                    deactivate Rep

                    CTRL -> PLAT : getPropertyTypeRepository()
                    activate PLAT

                    PLAT --> CTRL : propertyTypeRepository
                    deactivate PLAT

                    CTRL -> ProType :getPropertyTypeByName(String propertyTypeName)
                    activate ProType

                    ProType --> CTRL : propertyType
                    deactivate ProType

                autonumber 5.2
                CTRL --> CTRL : propertyType
            deactivate CTRL

            CTRL -> CTRL : getTypeOfBusinessByName(String typeOfBusinessName)
                        activate CTRL

                            activate CTRL
                                CTRL -> Rep : getInstance()

                                activate Rep

                                Rep --> CTRL: repositories
                                deactivate Rep

                                CTRL -> PLAT : getTypeOfBusinessRepository()
                                activate PLAT

                                PLAT --> CTRL : typeOfBusinessRepository
                                deactivate PLAT

                                CTRL -> ProType :getTypeOfBusinessByName(String typeOfBusinessName)
                                activate ProType

                                ProType --> CTRL : typeOfBusiness
                                deactivate ProType

                            <-- CTRL: typeOfBusiness
                            deactivate CTRL

                            CTRL --> CTRL : typeBusiness
                        deactivate CTRL

            CTRL -> CTRL : getAdministratorFromSession()
            activate CTRL

                CTRL -> _APP: getInstance()
                        activate _APP
                            _APP -> CTRL: appSession
                        deactivate _APP

                        CTRL -> APP: getCurrentSession()
                        activate APP

                            APP --> CTRL: currentSession
                        deactivate APP

                        CTRL -> SESSAO: email = getUserEmail()
                        activate SESSAO

                            SESSAO --> CTRL: email
                        deactivate SESSAO

                        CTRL -> PLAT: getEmployeeRepository(email)
                        activate PLAT

                            PLAT --> CTRL: employeeRepository
                        deactivate PLAT

                        CTRL -> EmployeeRepository: getEmployeeByEmail(email)
                        activate EmployeeRepository

                            Employee --> CTRL : administrator
                        deactivate EmployeeRepository

                CTRL -> CTRL : administrator
            deactivate CTRL

            CTRL -> CTRL: readFile(fileName)
            activate CTRL
            CTRL -> PropertyRepository: createProperty(information)
            activate PropertyRepository

                ref over PropertyRepository
                    Create Property

                end
                autonumber 5.10
                opt land
                PropertyRepository --> CTRL : land
                end
                autonumber 5.10
                opt apartment
                PropertyRepository --> CTRL: apartment
                end
                autonumber 5.10
                opt house
                PropertyRepository --> CTRL: house
                end
            deactivate PropertyRepository
            autonumber 5.11

            CTRL -> RequestRepository: createRequest(information)
            activate RequestRepository
                ref over RequestRepository
                                    Create Request

                end
                RequestRepository --> CTRL: request
                deactivate RequestRepository

           CTRL -> AnnouncementRepository: createAnnouncement(information)
                       activate AnnouncementRepository
                           ref over AnnouncementRepository
                                               Create Announcement

                           end
                           AnnouncementRepository --> CTRL: announcement
                           deactivate AnnouncementRepository
          CTRL -> AgencyRepository: createAgency(information)
                                 activate AgencyRepository
                                     ref over AgencyRepository
                                                         Create Agency

                                     end
                                     AgencyRepository --> CTRL: agency
                                     deactivate AgencyRepository
          CTRL --> CTRL
          deactivate CTRL
          CTRL --> UI
          deactivate CTRL
          autonumber 6
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM
@enduml