@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "taskCategoryRepository:\nTaskCategoryRepository" as TaskCategoryRepository

autonumber 12
-> CTRL : readFile(fileName)

autonumber 12.1

activate CTRL
    group Read File
        CTRL -> CTRL : readFile(fileName)
        activate CTRL

        CTRL -> Owner : insertInformationAboutOwner(ownerName, ownerCCNumber, ownerTaxNumber, ownerCCNumber, taxNumber,)
        activate CTRL
            Owner -> Owner: addOwner(name, ccNumber, taxNumber, emailAddres, phoneNumber)

        CTRL -> PLAT : getTaskCategoryRepository()
        activate PLAT

            PLAT -> CTRL : taskCategoryRepository
        deactivate PLAT

        CTRL -> TaskCategoryRepository : getTaskCategoryByDescription(taskCategoryDescription)
        activate TaskCategoryRepository

            TaskCategoryRepository --> CTRL : taskCategory
        deactivate TaskCategoryRepository

    end group

    autonumber 13
    <-- CTRL : taskCategory

deactivate CTRL


@enduml