@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "owner:\n:Owner" as Owner
participant "fileReader\n:FileReader" as TAREFA

autonumber 16
-> ORG: readFile(file, administrator)

autonumber 16.1
activate ORG
    group Read File

        ORG -> TAREFA**: readFile(file, administrator)

        activate ORG
        activate Owner
            TAREFA -> TAREFA: FileReader(file, administrator)
            activate TAREFA
                TAREFA --> Owner
                deactivate TAREFA
                    Owner -> Owner: createOwner(name, ccNumber, taxNumber, emailAddress, phoneNumber)
                    activate Owner
            Owner --> Owner
            deactivate Owner
            activate TAREFA
                TAREFA --> ORG
                deactivate TAREFA
                    ORG -> ORG: createProperty(type, area, distanceFromCityCentre, photos)


            ORG --> ORG
        deactivate ORG
    end

    autonumber 17
    <-- ORG : task
deactivate ORG


@enduml