@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":ImportInformationController" as CTRL
participant ":Repositories" as Rep
participant "repositories\n:Repositories" as PLAT
participant "typeOfBusinessRepository\n:TypeOfBusinessRepository" as typeOfBusinessRepository

autonumber 17
-> CTRL: getTypeOfBusinessByName(String typeOfBusinessName)

activate CTRL
    CTRL -> Rep : getInstance()

    activate Rep

    Rep --> CTRL: repositories
    deactivate Rep

    CTRL -> PLAT : getTypeOfBusinessRepository()
    activate PLAT

    PLAT --> CTRL : typeOfBusinessRepository
    deactivate PLAT

    CTRL -> ProType :getTypeOfBusinessByName(String typeOfBusinessName)
    activate ProType

    ProType --> CTRL : typeOfBusiness
    deactivate ProType

<-- CTRL: typeOfBusiness
deactivate CTRL
@enduml