@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "requestRepository\n:RequestRepository" as RequestRepository
participant "request\n:Request" as Request

autonumber 10.1
group Create Request
activate RequestRepository

opt sale
autonumber 10.1
-> RequestRepository: createSaleRequest(information)
opt land

        RequestRepository -> Request**: createSaleLandRequest(land, \nrequestedPrice, typeOfBusiness, owner)
end
autonumber 10.2
opt apartment

        RequestRepository -> Request** : createSaleApartmentRequest(apartment, \nrequestedPrice, typeOfBusiness, owner)
end
autonumber 10.2
opt House

        RequestRepository -> Request** : createSaleHouseRequest(house, \nrequestPrice, typeOfBusiness, owner)
end
            RequestRepository -> RequestRepository: addSaleRequest(saleRequest)
            deactivate Request
        activate RequestRepository
            RequestRepository -> RequestRepository: validateSaleRequest(saleRequest)
            activate RequestRepository
                RequestRepository --> RequestRepository
            deactivate RequestRepository

            RequestRepository --> RequestRepository
        deactivate RequestRepository
    end

opt rent
autonumber 10.1
-> RequestRepository: createRentRequest(information)
opt land

        RequestRepository -> Request**: createSaleLandRequest(land, \nrequestedPrice, typeOfBusiness, owner)
end
autonumber 10.2
opt apartment

        RequestRepository -> Request** : createSaleApartmentRequest(apartment, \nrequestedPrice, typeOfBusiness, owner)
end
autonumber 10.2
opt House

        RequestRepository -> Request** : createSaleHouseRequest(house, \nrequestPrice, typeOfBusiness, owner)
end
                RequestRepository -> RequestRepository: addRentRequest(rentRequest)
                deactivate Request
            activate RequestRepository
                RequestRepository -> RequestRepository: validateRentRequest(rentRequest)
                activate RequestRepository
                    RequestRepository --> RequestRepository
                deactivate RequestRepository

                RequestRepository --> RequestRepository
            deactivate RequestRepository

        end
        autonumber 11
        <-- RequestRepository : request
deactivate RequestRepository

@enduml