@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as Organization
participant "agency\n:Agency" as Agency

autonumber 10
-> Organization: createAgency(id, designation, location, \nemailAddress, telephoneNumber, administrator)

autonumber 10.1
activate Organization
    group Create Agency

        Organization -> Agency**: createAgency(id, designation, location, \nemailAddress, telephoneNumber, administrator)
            Organization -> Organization: addAgency(agency)
            deactivate Agency
        activate Organization
            Organization -> Organization: validateAgency(agency)
            activate Organization
                Organization --> Organization
            deactivate Organization

            Organization --> Organization
        deactivate Organization
    end

    autonumber 11
    <-- Organization : agency
deactivate Organization


@enduml