@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

hide footbox
actor " Real Estate Agent" as ADM
participant ": CreateRequestUI" as UI
participant ": CreateRequestController" as CTRL
participant ": RequestRepository" as RRP
participant ": AnoouncmentRepository" as ARP



activate ADM

        ADM -> UI :: Requests login

        activate UI
         activate CTRL
                    UI -> CTRL : uiSendLoginRequest()
                    activate RRP
                    CTRL -> RRP :sendLoginRequest()

            CTRL->UI  : requestLoginData()

            UI-> ADM : uiDisplayLoginRequest()
            ADM --> UI: Inserts login data

             alt

             UI-> CTRL : uiSendLoginData()
             CTRL--> UI : validateLoginData()
             UI --> ADM : displayValidLoginData()



              UI-> CTRL : uiSendLoginData()
                          CTRL--> UI : validateLoginData()
                          UI --> ADM : displayValidLoginData()


             end alt

ADM -> UI : requests sale announcment publish
UI -> CTRL: uiRequestSaleAnnouncmentPublish()
CTRL -> RRP : sendSaleAnnoucmentRequest()
CTRL -> UI: rquestSaleAnnouncmentData()
deactivate RRP
UI -> ADM : Displays the request data for sale
ADM --> UI : Introduces the sale data

 alt

             UI-> CTRL : uiSendLoginRequestData()
             CTRL--> UI : validateLoginRequestData()
             UI --> ADM : displayValidLoginRequestData()



              UI-> CTRL : uiSendLoginRequestData()
                          CTRL--> UI : validateLoginRequestData()
                          UI --> ADM : displayValidRequestLoginData()



             end alt






    deactivate UI

activate ARP
             CTRL -> ARP: publishSaleAnnouncment()
             deactivate ARP


deactivate ADM


@enduml