@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":CreateAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "propertyRepository:\nPropertyRepository" as PropertyRepository

autonumber 3

 -> CTRL : getProperties()
autonumber 3.1
activate CTRL
    group Get Property List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getPropertyRepository()
            activate PLAT

                PLAT --> CTRL: propertyRepository
            deactivate PLAT

            CTRL -> TaskCategoryRepository : getProperties()
            activate TaskCategoryRepository

                TaskCategoryRepository --> CTRL : propertyList
            deactivate TaskCategoryRepository


    end
    autonumber 4
    <-- CTRL  : propertyList
deactivate CTRL


@enduml