@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":PublishAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "propertyRepository:\nPropertyRepository" as TaskCategoryRepository

autonumber 12
-> CTRL : getTaskCByDescription(taskCategoryDescription)

autonumber 12.1

activate CTRL
    group Get Task Category
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getPropertyRepository()
        activate PLAT

            PLAT -> CTRL : propertyRepository
        deactivate PLAT

        CTRL -> TaskCategoryRepository : getTaskCategoryByDescription(taskCategoryDescription)
        activate TaskCategoryRepository

            TaskCategoryRepository --> CTRL : property
        deactivate TaskCategoryRepository

    end group

    autonumber 13
    <-- CTRL : taskCategory

deactivate CTRL


@enduml