@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title User Story 008 - System Sequence Diagram (SSD)


autonumber



actor "Real Estate Agent" as Agent
participant "System" as System



activate Agent
activate System

System --> Agent : requests login
deactivate System
Agent -> System : inserts loign data (id/email , password )
activate System

System --> Agent: displays agent menu
deactivate

Agent -> System : requests to see property announcment requests




activate System
    System --> Agent: displays the announcments request list sorted by the date they were created, with the most recent requests appearing first.
    deactivate System


    Agent -> System : selects a property announcment request

    activate System

    System--> Agent: asks for request acceptance
     deactivate System
   Agent-> System: accepts request

   activate System
System --> Agent : informs the agent the announcment has been published












@enduml