@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Organization Employee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to show the list of property announcement requests
    activate System

        System --> Employee : show the list
    deactivate System

    Employee -> System : asks to sort announcement requests list by the date that they \nare created(most recent requests appearing first)
    activate System

        System --> Employee : shows the list sorted
    deactivate System


   loop select a request

   Employee -> System : select a request
   activate System

    System --> Employee : shows the status of the request
    deactivate System

   opt request is accepted
    Employee -> System : post the announcement
    activate System

        System --> Employee : delete the submitted request from the list of requests
    deactivate System

    end
    end

    Employee -> System : submits the refreshed list
    activate System

        System --> Employee : display operation sucess

    deactivate System

@enduml