@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor white
}

'title Use Case Diagram Example

top to bottom direction

rectangle "Use Cases" as usecases{
    usecase "UC4 - To submit a request" as UC4
    Owner --> UC4
    usecase "UC3 - To register an employee" as UC3
    SystemAdministrator --> UC3
    usecase "UC5 - To register a store" as UC5
    SystemAdministrator --> UC5
    usecase "UC8 - To select a request and publish an announcement" as UC8
Agent--> UC8


    usecase "UC2 - To publish an announcement" as UC2
    Agent --> UC2
    usecase "UC1 - To display listed properties \n(unregistered user)" as UC1
    UnregisteredUser --> UC1
    }


@enduml