@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor white
}

'title Use Case Diagram Example

top to bottom direction

rectangle "Use Cases" as usecases{
    usecase "UC13" as UC13
    usecase "UC12 - To import information from a legacy system" as UC12
    SystemAdministrator--> UC12
    usecase "UC11" as UC11
    usecase "UC10" as UC10
    usecase "UC9" as UC9
    usecase "UC8 - To select a request and publish an announcement" as UC8
    Agent--> UC8
 }


@enduml