@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as Organization
participant "store\n:Store" as Store

autonumber 10
-> Organization: registerStore(id, designation, location, \nemailAddress, telephoneNumber, administrator)

autonumber 10.1
activate Organization
    group Register Store

        Organization -> Store**: registerStore(id, designation, location, \nemailAddress, telephoneNumber, administrator)
            Organization -> Organization: addStore(store)
            deactivate Store
        activate Organization
            Organization -> Organization: validateStore(store)
            activate Organization
                Organization --> Organization
            deactivate Organization

            Organization --> Organization
        deactivate Organization
    end

    autonumber 11
    <-- Organization : store
deactivate Organization


@enduml