@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant "ListVisitRequestUI" as UI
participant "ListVisitRequestController" as CTRL
participant "Repositories" as Rep
participant "repositories\n:Repositories" as PLAT
participant "taskCategoryRepository:\nTaskCategoryRepository" as TaskCategoryRepository
participant "visitRequest " as VisReq
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESS
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG
participant "task\n:Task" as TAREFA
participant "visitRepository: \nVisitRepository" as VisRep
participant "visitRequestList\n List<VisitRequest>" as VisReqList
participant "algorithm: \n SortingAlgorithm" as ALG

activate ADM

        ADM -> UI : request to list booking requests

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create


            activate CTRL

                CTRL -> Rep : getInstance()
                activate Rep

                    Rep --> CTRL: repositories
                deactivate Rep


            CTRL -> _APP : getInstance()
            activate _APP

            _APP --> CTRL : appSession
            deactivate _APP

            CTRL -> APP : getCurrentSession()
            activate APP

            APP --> CTRL : currentSession
            deactivate APP

                CTRL -> PLAT : getVisitRepository()
                activate PLAT

                    PLAT --> CTRL: visitRepository
                deactivate PLAT

                CTRL -> VisRep : getVisitList()
                activate VisRep

                    VisRep --> CTRL : visitList
                deactivate VisRep

                CTRL --> UI : visitList


            deactivate CTRL



        UI --> ADM : asks the begin date
    deactivate UI

    ADM -> UI :  submits the begin date
    activate UI

    UI--> UI : save the begin date

        UI --> ADM : asks the end date
    deactivate UI

    ADM -> UI : submits the end  date
    activate UI

     UI--> UI : save the end date

    UI --> ADM : asks to confirm the file name and types of algorithm
    deactivate UI

    ADM -> UI : Confirms the file name and types of algorithm
    activate UI

    UI -> CTRL : getListVisit(fileName, startDate, endDate)
    activate CTRL

    CTRL -> SESS : getUserEmail()
    activate SESS

    SESS --> CTRL : getUserEmail
    deactivate SESS

    CTRL -> VisRep : getListVisitRequest(userEmail, fileName, startDate, endDate)
    activate VisRep

loop for each visit request

    VisRep -> VisReqList : creates()

    alt visitRequest.getAgentEmail() == userm«Email

    VisRep -> VisReqList : add(visitRequest)
    activate VisReqList
    deactivate VisReqList

end
end

    VisRep -> VisRep : sortList

    VisRep -> VisRep : filterByDate(visitRequestList, beginDate , endDate)

    VisRep -> ALG : sort(beginDate, endDate)
    activate ALG

    ALG --> VisRep : visitRequestList
    deactivate ALG

    VisRep --> CTRL : visitRequestList
    deactivate VisRep

deactivate ADM

@enduml