@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class SystemAdministrator {
    username
    password
}

class Store {
    id
    designation
    location
    emailAddress
    phoneNumber
}

class Employee {
}

class Agent{
}

class Owner{
}

SystemAdministrator "1" - "1..*" Store : registers >
Store "1" -- "1..*" Employee : has >
Employee "1..*" - "1" SystemAdministrator : registered by >
Employee "1..*" - "1" Agency : assigned at >
Agency "1" - "1" Store : has >
Agency "1" - "1..*" Agent : has >
Owner "1" -- "1..*" Agent : contacts >
@enduml