@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox
participant ":CreateTaskController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "clientRepository:\nClientRepository" as ClientRepository

autonumber 9.4
-> CTRL : getClientFromSession()
autonumber 9.4.1
activate CTRL

    group Get Employee
        CTRL -> _APP: getInstance()
        activate _APP
            _APP -> CTRL: appSession
        deactivate _APP

        CTRL -> APP: getCurrentSession()
        activate APP

            APP --> CTRL: currentSession
        deactivate APP

        CTRL -> SESSAO: email = getUserEmail()
        activate SESSAO

            SESSAO --> CTRL: email
        deactivate SESSAO

        CTRL -> PLAT: getClientRepository(email)
        activate PLAT

            PLAT --> CTRL: clientRepository
        deactivate PLAT

        CTRL -> ClientRepository: getClientByEmail(email)
        activate ClientRepository

            ClientRepository --> CTRL : client
        deactivate ClientRepository
    end
    autonumber 9.5
    <-- CTRL : client
deactivate CTRL

@enduml