@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "User\n(unregistered)" as ADM
participant ":System" as System


activate ADM

        ADM -> System : pass the credentials
        activate System

        System -> System : validateUser()

        System -> ADM : return validation value
        deactivate System

deactivate ADM

@enduml