@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "User\n(unregistered)" as ADM
participant ":System" as System
participant ":PropertiesList" as List
participant ":Filter" as Filter


activate ADM

        ADM -> System : selects
        activate System

            System -> Filter : createFilter()
            activate Filter

            Filter -> System : defineCriteria()
            deactivate Filter

            System -> List : searchPropertiesByFilter()
            activate List

            List -> System : getPropreties()
            deactivate List

        System -> ADM : pass the information
        deactivate System

deactivate ADM

@enduml