@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "User\n(unregistered)" as ADM
participant ":System" as System
participant ":PropertiesList" as List
participant ":DisplayOfProperties" as Display


activate ADM

        ADM -> System : request list of properties
        activate System

            System -> List : loadProperties()
            activate List

            List -> System : getPropreties()
            deactivate List

            System -> Display : display()
            activate Display

            Display -> System : pass the information

            deactivate Display

        System -> ADM : display de information
        deactivate System




@enduml