@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Real Estate Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to see the booking request list
    activate System

        System --> Agent : shows the booking request list
    deactivate System

    Agent -> System : selects a booking request
    activate System

    System --> Agent : shows data of the selecting booking request
    deactivate System

opt want to responde to scheduled request
loop want to responde to scheduled request


    Agent -> System : write the response to the user
    activate System

        System --> Agent : send the response
    deactivate System

 end
 end

@enduml