@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":CreateRequestController" as CTRL
participant ":Repositories" as Rep
participant "repositories\n:Repositories" as PLAT
participant "RequestTypeRepository:\nRequestTypeRepository" as TaskCategoryRepository

autonumber 3
CTRL -> Rep : getInstance()
                activate Rep

                    Rep --> CTRL: repositories
                deactivate Rep

                CTRL -> PLAT : getRequestCategoryRepository()
                activate PLAT

                    PLAT --> CTRL: requestCategoryRepository
                deactivate PLAT

                CTRL -> TaskCategoryRepository : getRequestTypeRepository()
                activate TaskCategoryRepository

                    TaskCategoryRepository --> CTRL : requestTypeList
                deactivate TaskCategoryRepository


@enduml