@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "System Administrator" as Administrator
participant "System" as System
participant "Store" as Store

activate Administrator

    Administrator -> Store : asks to obtain information about the designation, location and local manager
    activate Store

        Store --> Administrator : send the information
    deactivate Store

    Administrator -> System : insert the information
    activate System

    System --> Administrator: keep the information

        Administrator -> System : submits the information
        deactivate Administrator

    System -> Store : display the designation, location and local manager
    activate Store

@enduml