@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Network Manager" as Manager
participant ":System" as System

activate Manager

    Manager -> System : asks to create list of all employees sorted by store
    activate System

        System --> Manager : displays list of all employees sorted by store
    deactivate System

@enduml